export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_WITH_TOKEN = 'USER_WITH_TOKEN';

export const USER_REGISTER_FIELD_CHANGE = 'USER_REGISTER_FIELD_CHANGE';
export const USER_LOGIN_FIELD_CHANGE = 'USER_LOGIN_FIELD_CHANGE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const DISMISS_PASSWORD_MESSAGE = 'DISMISS_PASSWORD_MESSAGE';
export const DISMISS_EMAIL_MESSAGE = 'DISMISS_EMAIL_MESSAGE';
export const DISMISS_SERVER_ERROR_MESSAGE = 'DISMISS_SERVER_ERROR_MESSAGE';
export const DISMISS_REGISTER_MESSAGE = 'DISMISS_REGISTER_MESSAGE';
export const DISMISS_LOGIN_MESSAGE = 'DISMISS_LOGIN_MESSAGE';
export const DISMISS_LOGIN_SERVER_ERROR_MESSAGE = 'DISMISS_LOGIN_SERVER_ERROR_MESSAGE';
export const DISMISS_FETCH_ERROR_MESSAGE = 'DISMISS_FETCH_ERROR_MESSAGE';
export const DISMISS_REMOVE_MESSAGE = 'DISMISS_REMOVE_MESSAGE';

export const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_ERROR = 'FETCH_FILES_ERROR';
export const FILE_UPLOAD_ITEM = 'FILE_UPLOAD_ITEM';
export const FILE_REMOVE_ITEM = 'FILE_REMOVE_ITEM';


export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';

export const FILE_REMOVE_REQUEST = 'FILE_REMOVE_REQUEST';
export const FILE_REMOVE_SUCCESS = 'FILE_REMOVE_SUCCESS';
export const FILE_REMOVE_ERROR = 'FILE_REMOVE_ERROR';

export const PASSWORD_MATCH_ERROR = 'PASSWORD_MATCH_ERROR';